# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chorctl < Formula
  desc "Management CLI for chorus service"
  homepage "https://github.com/clyso/chorus"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clyso/chorus/releases/download/v0.6.0/chorctl_v0.6.0_darwin_amd64.tar.gz"
      sha256 "e18a2ef56cdfbcc3149b2d594309c343a25265b1ebeed5248adffc799174878a"

      def install
        bin.install "chorctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clyso/chorus/releases/download/v0.6.0/chorctl_v0.6.0_darwin_arm64.tar.gz"
      sha256 "cab61f76502cc9112c8108920bdcb9e64b6fd04cd80abe8b7e55c03490f9b624"

      def install
        bin.install "chorctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/clyso/chorus/releases/download/v0.6.0/chorctl_v0.6.0_linux_amd64.tar.gz"
      sha256 "82e2351f91f0fa12a01bf74e5151304714ae70e4a3709ca273ce27546748aebc"

      def install
        bin.install "chorctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clyso/chorus/releases/download/v0.6.0/chorctl_v0.6.0_linux_arm64.tar.gz"
      sha256 "94e4c5cc779b0fcb4dceb97dcc08d2def6b44c31d4b866fc94a312b4cca07713"

      def install
        bin.install "chorctl"
      end
    end
  end

  test do
    system "#{bin}/chorctl --version"
  end
end
