# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chorctl < Formula
  desc "Management CLI for chorus service"
  homepage "https://github.com/clyso/chorus"
  version "0.7.3"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/clyso/chorus/releases/download/v0.7.3/chorctl_v0.7.3_darwin_amd64.tar.gz"
      sha256 "8d4a57a3d748c70d50095da2966f6f6959f7c85c2e01ee7b6fb2a73ffa36e1fc"

      def install
        bin.install "chorctl"
      end
    end
    on_arm do
      url "https://github.com/clyso/chorus/releases/download/v0.7.3/chorctl_v0.7.3_darwin_arm64.tar.gz"
      sha256 "cfa3ca42a6a097edf0135fbc8998b98e0c57cc10c29db94f0e6e4c92fccd3f6e"

      def install
        bin.install "chorctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clyso/chorus/releases/download/v0.7.3/chorctl_v0.7.3_linux_amd64.tar.gz"
        sha256 "61795f4d17ae918efbe771a6bf75157b21cf17137524f0ac9f4c20de3ed7b47a"

        def install
          bin.install "chorctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clyso/chorus/releases/download/v0.7.3/chorctl_v0.7.3_linux_arm64.tar.gz"
        sha256 "64a83e07a4f71ee40e1f7f356a6ae1718db2d8ba888431e0ee5148242168a42b"

        def install
          bin.install "chorctl"
        end
      end
    end
  end

  test do
    system "#{bin}/chorctl --version"
  end
end
